### ISSUE TITLE
Getting issue for HP scanjet 5590

### ISSUE THREAD

**Issue by deepd07mane** [caspark/snapsy#1]
When scanning pages on scanjet 5590 getting exception in CloseSrc() function for DSMident()
Error Message: **Attempted to read or write protected memory. This is often an indication that other memory is corrupt.** 
Operating System : Windows 10
Scanner : HP ScanJet 5590

Please help to resolve the same

**Comment by caspark** [comment]
I'm sorry, but as mentioned in the readme, this project is unmaintained. Even if it weren't, I have no hope in hell of debugging a printer-specific issue like that without having the exact model of printer handy and a lot more knowledge of driver-debugging.

To assist with your debugging, I suggest scanning images first, then using a separate application to turn them into PDFs. Good luck!
